### ISSUE TITLE
Opening .w12p or .w13p gives a Load Error

### ISSUE THREAD

**Issue by Fexty12573** [Synthlight/MHW-Editor#10]
When I try to open either .w12p or .w13p with the newest version of the editor it gives me this error:

 ---------------------------
Load Error
---------------------------
Error occured. Press Ctrl+C to copy the contents of ths window and report to the developer.

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.

   at System.IO.BinaryReader.ReadByte()

   at MHW_Editor.Weapons.Wp12Param.Shield_Mods.LoadData(BinaryReader reader) in R:\Games\Monster Hunter World\MHW-Editor\Generated\MHW_Editor\Weapons\Wp12Param.cs:line 5721

   at MHW_Editor.Weapons.Wp12Param.LoadFile(String targetFile) in R:\Games\Monster Hunter World\MHW-Editor\Generated\MHW_Editor\Weapons\Wp12Param.cs:line 6235

   at MHW_Editor.Models.CustomSaveLoad`1.LoadData(String targetFile) in R:\Games\Monster Hunter World\MHW-Editor\Models\CustomSaveLoad.cs:line 8

   --- End of inner exception stack trace ---

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)

   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at MHW_Editor.MainWindow.Load() in R:\Games\Monster Hunter World\MHW-Editor\MainWindow.xaml.cs:line 650
```

**Picture of the error:**

![Annotation 2020-04-30 202529](https://user-images.githubusercontent.com/60443001/80745742-0b6b8980-8b21-11ea-99aa-f5020dd9926e.jpg)

**Comment by Synthlight** [comment]
You are trying to open an outdated w12p file. You MUST always pull the most recent copy from the chunk that has it.
I can replicate the exact error bu opening w12p from G0. Use the search button in the editor to know the most recent chunk a file is in, or merge your chunks when extracting.

![image](https://user-images.githubusercontent.com/1075166/80749613-b154cf00-8af4-11ea-89bd-37568592767e.png)

As new weapons get added these files change size. The error does not occur if you use the correct version of the file.

I really need to add the hash/size check to these files so I'm leaving the issue open till then. That should hopefully prevent this in the future.

**Comment by Fexty12573** [comment]
Yes that solved it. Thank you for your quick answer, in hindsight, the chunk version should've been the first thing I checked but that kinda slipped my mind I guess.

Anyway thank you for the continued support on this!

**Comment by Synthlight** [comment]
Next version will use the same hash check as normal load:
![image](https://user-images.githubusercontent.com/1075166/80775461-af5b3200-8b2d-11ea-9758-f97094edcb36.png)
